name: fiszkomaniak
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-169.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.4
  firebase_core: ^1.3.0
  firebase_auth: ^3.3.9
  firebase_storage: ^10.2.15
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  hexcolor: ^2.0.6
  material_design_icons_flutter: ^5.0.6595
  flutter_keyboard_visibility: ^5.2.0
  equatable: ^2.0.3
  cloud_firestore: ^3.1.10
  rxdart: ^0.27.3
  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  firebase_auth_mocks: ^0.8.2
  flutter_speed_dial: ^5.0.0+1
  localization: ^2.1.0
  flip_card: ^0.6.0
  image_picker: ^0.8.5
  cached_network_image: ^3.2.0
  syncfusion_flutter_charts: ^20.1.55
  flutter_local_notifications: ^9.5.3+1
  flutter_launcher_icons: ^0.9.2
  timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_launcher.png"
